# Generated by Django 4.0.1 on 2022-02-25 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0009_remove_taskhistory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEmail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mail_time', models.IntegerField(default=0)),
            ],
        ),
    ]
