# Generated by Django 4.0.1 on 2022-02-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_taskemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskhistory',
            old_name='task_id',
            new_name='task',
        ),
    ]
