# Generated by Django 4.0.1 on 2022-02-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_rename_task_id_taskhistory_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskemail',
            name='email_prev_sent_at',
            field=models.IntegerField(default=0),
        ),
    ]
